# Generated by Django 5.1.2 on 2024-11-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuarios_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
    ]
