# Generated by Django 5.1.2 on 2024-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuarios_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
